### ISSUE TITLE
:unneeded is deprecated

### ISSUE THREAD

**Issue by majouji** [tophat/homebrew-bar#48]
**Describe the bug**
Homebrew is giving the following warning after upgrading it to 3.3.0:

```sh
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tophat/bar tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/tophat/homebrew-bar/Formula/yvm.rb:9
```

**To Reproduce**
1. `brew upgrade && brew cleanup` while having the tap installed.

**Screenshots**

<img width="929" alt="image" src="https://user-images.githubusercontent.com/23482161/138710413-24a691e9-30b9-433e-8168-5eae93c6641c.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.0.1

**Comment by iamogbz** [comment]
Fixes tophat/yvm/issues/1007
